language: php
sudo: true
php:
  - 5.5
  - 5.4
  - hhvm

script: phpunit Test.php
  - cat /sys/kernel/mm/transparent_hugepage/enabled
  - sudo echo never> /sys/kernel/mm/transparent_hugepage/enabled
  - cat /sys/kernel/mm/transparent_hugepage/defrag
  - sudo echo never> /sys/kernel/mm/transparent_hugepage/defrag
